### ISSUE TITLE
Interface That Handle Connection to the ROS 2 Web Bridge Server

### ISSUE THREAD

**Issue by threeal** [ichiro-its/shisen-app#1]
As in the [Shisen RVue](https://github.com/ichiro-its/shisen-rvue/), the first part that needs to be done before continuing to the configuration interface is handling connection to the [ROS 2 Web Bridge Server](https://github.com/RobotWebTools/ros2-web-bridge). I suggest the component should be shown as a single small card in the center, with a WebSocket URL input and a connect button.
![image](https://user-images.githubusercontent.com/10202888/109895690-38994300-7cc2-11eb-975f-e17fdd080188.png)

To make the interface conformable with the React's design, serve the component with an if-else statement:
```js
const [connected, setConnected] = useState(false);

if (connected) {
  // main interface
  return (<div> ... </div>);
} else {
  // connection interface
  return (<div> ... </div>);
}
```

Next, handle the `connected` state using [roslibjs](https://www.npmjs.com/package/roslib). Call `setConnected` to true inside the `connection` callback, and call `setConnected` to false inside the `error` and `close` callback.
```js
const ros = new ROSLIB.Ros();

ros.on('connection', () => {
  setConnected(true);
  ...
});

ros.on('error', () => {
  setConnected(false);
  ...
});

ros.on('close', () => {
  setConnected(false);
  ...
});

ros.connect('ws://localhost:9090');
```

**Comment by BryanYehuda** [comment]
Mas Alfi, assign aku Mas

**Comment by finesaaa** [comment]
assign aku mas
